# STAGE 1 -> BUILD OF REACT PROJECT
FROM node:19.4.0-alpine3.16 AS build

WORKDIR /react-shop

COPY package.json ./

RUN npm install

COPY . . 

RUN npm run build

# STAGE 2 -> CREATE NGINX SERVER
FROM nginx:1.23.3-alpine AS prod-stage

COPY --from=build ["/react-shop/build", "/usr/share/nginx/html"]

EXPOSE 3000

CMD ["nignx", "-g", "daemon off;"]